replicaCount: 1

image:
  repository: docker.io/istio/proxyv2
  tag: 1.14.1
  pullPolicy: IfNotPresent

serviceAccount:
  name: istio-ingressgateway-service-account

resources:
  limits:
    cpu: 2000m
    memory: 1024Mi
  requests:
    cpu: 10m
    memory: 40Mi

affinity: {}

ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  - name: https
    containerPort: 8443
    protocol: TCP
  - name: tcp
    containerPort: 31400
    protocol: TCP
  - name: tls
    containerPort: 15443
    protocol: TCP
  - name: prometheus
    containerPort: 15090
    protocol: TCP
  - name: healthz
    containerPort: 15021
    protocol: TCP