##################################################################################################
# fronend
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
    service: frontend
spec:
  selector:
    app: frontend-app
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
---
#################################################################################################
# deployment v1
##################################################################################################
apiVersion: apps/v1s
kind: Deployment
metadata:
  name: frontend-v1
  labels:
    app: frontend-app
    service: frontend
    version: v1
spec:
  selector:
    matchLabels:
      app: frontend-app
      version: v1
  template:
    metadata:
      labels:
        app: frontend-app
        version: v1
    spec:
      serviceAccountName: frontend-sa
      containers:
        - name: frontend-app
          image: yuyatinnefeld/microservice-frontend-app:1.0.0
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10