replicaCount: 1
image:
  repository: docker.io/istio/pilot
  tag: 1.14.1
  pullPolicy: IfNotPresent

serviceAccount:
  name: istiod

resources:
  requests:
    cpu: 10m
    memory: 100Mi

volumes:
  - name: local-certs
    emptyDir:
      medium: Memory
  - name: istio-token
    projected:
      sources:
        - serviceAccountToken:
            audience: istio-ca
            expirationSeconds: 43200
            path: istio-token
  - name: cacerts
    secret:
      optional: true
      secretName: cacerts
  - name: istio-kubeconfig
    secret:
      optional: true
      secretName: istio-kubeconfig
