apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-golang-app-deploy
  labels:
    app: http-golang-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  http-golang-app
  template:
    metadata:
      labels:
        app:  http-golang-app
    spec:
      containers:
        - name: http-golang-app
          image: yuyatinnefeld/golang-app:2.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: http-golang-service
spec:
  selector:
    app:  http-golang-app
  ports:
    - port: 8888
      targetPort: 8888
      name: http-frontend
  type: LoadBalancer